#!/usr/bin/env bash

set -e

main() {
	send editor
	nvim .
}

# @cmd Runs the game
game() {
	godot
}

# @cmd Runs the editor
editor() {
	godot -e
}

# @cmd Builds and runs the game
build() {
	mkdir -p builds/Linux builds/web
	godot --headless --export-release Linux builds/Linux/waves.x86_64
	godot --headless --export-release Web builds/web/waves.html
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
