#!/usr/bin/env bash

set -e

main() {
	send editor
	nvim .
}

# @cmd Runs the game
game() {
	godot
}

# @cmd Runs the editor
editor() {
	godot -e
}

# @cmd Builds and runs the game
build() {
	echo TODO: build
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
